config/routes.rb
Rails.application.routes.draw do
  resources :sites

  root 'welcome#index'

  get 'about' => 'welcome#about'

end

app/models/site.rb
class Site < ActiveRecord::Base
	has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"

 	validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/sites_controller.rb
class SitesController < ApplicationController
  before_action :set_site, only: [:show, :edit, :update, :destroy]

  # GET /sites
  # GET /sites.json
  def index
    @sites = Site.all.order(:id)
  end

  # GET /sites/1
  # GET /sites/1.json
  def show
    @sites = Site.all.order(:id)
  end

  # GET /sites/new
  def new
    @site = Site.new
    @sites = Site.all.order(:id)
  end

  # GET /sites/1/edit
  def edit
    @sites = Site.all.order(:id)
  end

  # POST /sites
  # POST /sites.json
  def create
    @site = Site.new(site_params)

    respond_to do |format|
      if @site.save
        format.html { redirect_to @site, notice: 'Site was successfully created.' }
        format.json { render :show, status: :created, location: @site }
      else
        format.html { render :new }
        format.json { render json: @site.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sites/1
  # PATCH/PUT /sites/1.json
  def update
    respond_to do |format|
      if @site.update(site_params)
        format.html { redirect_to @site, notice: 'Site was successfully updated.' }
        format.json { render :show, status: :ok, location: @site }
      else
        format.html { render :edit }
        format.json { render json: @site.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sites/1
  # DELETE /sites/1.json
  def destroy
    @site.destroy
    respond_to do |format|
      format.html { redirect_to sites_url, notice: 'Site was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_site
      @site = Site.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def site_params
      params.require(:site).permit(:url, :description, :title, :avatar)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  	@sites = Site.all.order(:id)
  end

  def about
  	@sites = Site.all.order(:id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sites_helper.rb
module SitesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Doug Graiser's Portfolio</title>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/css/bootstrap.min.css">
  <%= stylesheet_link_tag 'bootstrap', media: 'all' %>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/js/bootstrap.min.js"></script>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>

<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Doug Graiser's Portfolio", root_path, class: "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to "About", about_path %></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">My Sites <span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
          	<% @sites.each do |site| %>
          		<% if site != @sites.last %>
            		<li><%= link_to site.title, site %> </li>
            		<li class="divider"></li>
            	<% else %>
            		<li><%= link_to site.title, site %> </li>
            	<% end %>
            <% end %>
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

<%= yield %>

</body>
</html>

app/views/sites/_form.html.erb
<%= form_for(@site) do |f| %>
  <% if @site.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@site.errors.count, "error") %> prohibited this site from being saved:</h2>

      <ul>
      <% @site.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :title %><br>
    <%= f.text_field :title, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :url %> (Do not include "http/https://")<br>
    <%= f.text_field :url, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :description %><br>
    <%= f.text_area :description, class: "form-control", rows: 4 %>
  </div>
  <div class="field">
    <%= f.label "Choose an image:" %><br />
    <%= f.file_field :avatar, class: "white-text" %>
  </div>
  <br />
  <div class="actions">
    <%= f.submit "Submit", class: "btn btn-default" %>
  </div>
<% end %>

app/views/sites/edit.html.erb
<div class="row">
	<div class="col-md-4 col-md-offset-4 text-box">		
		<h1>Editing Site</h1>

		<%= render 'form' %>

		<br>
		&nbsp
		<%= link_to 'Show', @site %> |
		<%= link_to 'Back', sites_path %>
		<br>
		&nbsp
	</div>
</div>

app/views/sites/index.html.erb
<div class="container text-box">  
  <h1>Listing Sites</h1>

  <table class="table">
    <thead>
      <tr>
        <th>Title</th>
        <th>Url</th>
        <th>Description</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @sites.each do |site| %>
        <tr>
          <td><%= site.title %></td>
          <td><%= site.url %></td>
          <td><%= site.description %></td>
          <td><%= image_tag site.avatar.url(:thumb) %></td>
          <td><%= link_to 'Show', site %></td>
          <td><%= link_to 'Edit', edit_site_path(site) %></td>
          <td><%= link_to 'Destroy', site, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>

  <%= link_to 'New Site', new_site_path %>
  <br>
  &nbsp
</div>

app/views/sites/new.html.erb
<div class="row">
	<div class="col-md-4 col-md-offset-4 text-box">
		<h1>New Site</h1>

		<%= render 'form' %>

		<br>
		&nbsp
		<%= link_to 'Back', sites_path %>
		<br>
		&nbsp
	</div>
</div>

app/views/sites/show.html.erb
<div class="container text-box">
	<div class="row">
		<div class="col-md-4">	
			<p id="notice"><%= notice %></p>

			<h1><%= @site.title %></h1>

			<h3><a href="//<%= @site.url %>" target="_blank" title="<%= @site.title %>"><%= @site.url %></a></h3>

			<p>
			  <%= @site.description %>
			</p>
		</div>
		<div class="col-md-8">
			<p><%= image_tag @site.avatar.url, class: "show-pic" %></p>
		</div>
	</div>

</div>

app/views/welcome/about.html.erb
<div class="container text-box">
	<%= image_tag "dgraiser.jpg", alt: "Doug Graiser", class: "about-img" %>
	<h1>All About Me</h1>
	<p>I am a recent convert to programming. I was working in insurance claims for about five years or so, and then I lost my job due to cutbacks. If I had enjoyed my job, that might have been a bad thing. Instead, I decided to make lemonade with those lemons. After being out of work for about two weeks, I found my passion -- CODING!</p>
	<br />
	<p>I was lucky enough to find <%= link_to "Tech Talent South", "http://techtalentsouth.com", target: "_blank", title: "Tech Talent South" %>. I enrolled in a code immersion program where we learned Ruby on Rails, HTML/CSS, JavaScript/JQuery, SQL, git version control, and API's. I learned so much in that class and took right to it. <%= link_to "Click Here", "http://www.hypepotamus.com/people/doug-graiser-past-football-career-sparked-interest-startups/", target: "_blank", title: "http://www.hypepotamus.com/people/doug-graiser-past-football-career-sparked-interest-startups/" %> to see an article that I was featured in by Hypepotamus.</p>
	<br />
	<p>When I'm not coding or learning more about coding, I'm spending time with my wife and daughter. I also spend a lot of time in my garage building furniture or some other woodworking project. I love doing any kind of logic puzzle or jigsaw puzzle. My latest addiction has been doing <%= link_to "Paint By Number", "http://webpbn.com", target: "_blank", title: "Paint By Number" %> puzzles.</p>
</div>

app/views/welcome/index.html.erb
<div class="jumbotron">
	<div class="container">
	  <h1>Welcome to My Portfolio</h1>
	</div>
</div>
<div class="container">
	<div class="row">
		<% @sites.each do |site| %>
			<div class="col-md-6" id="gallery">
				<div class="panel panel-default">
				  <div class="panel-heading">
				    <h3 class="panel-title"><%= site.title %></h3>
				  </div>
				  <div class="panel-body">
				  	<%= link_to image_tag(site.avatar.url), site, class: "home-site-img" %>
				  	<div>&nbsp</div>
				  	<div class="row">
				  		<div class="col-md-9">
				    		<p><%= site.description[0..115] %>...</p>
				    	</div>
				    	<div class="col-md-3 btn-padding">
				    		<%= link_to "Read More", site, class: "btn btn-default btn-lg no-text-dec" %>
				    	</div>
				    </div>
				  </div>
				</div>
			</div>
		<% end %>
	</div>
</div>